name: gps-analysis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - pygeos
  - pyrobuf
  - cython
  - codecov
  - python-rapidjson
  - pip
  - geopandas
  - pytest-cov
  - pytest
  - python=3.7
  - jupyter
  - matplotlib
  - geoviews
  - gpxpy>=1.4.2
  - pyproj
  - holoviews
  - bokeh
  - numpy
  - scipy
  - jupyter
  - gdal
